packages:
  - packages/*
  - apps/*

catalog:
  "@primeuix/forms": ^0.1.0
  "@primeuix/styled": ^0.7.2
  "@primeuix/styles": ^1.2.3
  "@primeuix/themes": ^1.2.3
  "@primeuix/utils": ^0.6.1
  primeicons: ^7.0.0
  tailwindcss-primeui: ^0.6.1

catalogs:
  app:
    "@docsearch/js": ^3
    chart.js: 3.3.2
    nuxt: 3.15.4
    quill: 2.0.0
    sass: 1.45.0
    sass-loader: 8.0.2
    vite: 6.0.11
